config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^products/', include('test_products.products.urls', namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

test_products/products/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ProductsListView.as_view(), name='list'),
    url(r'^(?P<slug>[^/]+)/$', views.ProductView.as_view(), name='detail'),
    url(r'^(?P<slug>[^/]+)/like/$', views.ProductLikeView.as_view(), name='like'),
]

test_products/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='product_likes', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})


@python_2_unicode_compatible
class Comment(models.Model):
    text = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, related_name='comments')

    def __str__(self):
        return 'Comment {}'.format(self.text[:20])

test_products/products/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django import forms
from django.utils.translation import ugettext as _

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'cols': 60,
                'rows': 5,
                'placeholder': _('Write your comment here'),
                'required': True
            })
        }
        labels = {'text': ''}

test_products/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from datetime import timedelta

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import ListView, FormView, DetailView
from django.views.generic.base import View
from django.db.models import Prefetch
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.shortcuts import redirect, get_object_or_404
from django.db.models import Count
from django.utils import timezone
from braces.views import LoginRequiredMixin

from .models import Product, Comment
from .forms import CommentForm


class ProductsListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'products'
    paginate_by = settings.PRODUCT_PER_PAGE

    def get_queryset(self):
        order = 'pk'
        if self.request.GET.get('sort_direction') in ['asc', 'desc']:
            order = '-likes_num' if self.request.GET['sort_direction'] == 'asc' else 'likes_num'

        queryset = Product.objects.annotate(likes_num=Count('likes')).order_by(order)
        return queryset


class ProductView(FormView, DetailView):
    model = Product
    form_class = CommentForm
    template_name = 'products/product.html'
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('products:detail', kwargs={'slug': self.kwargs['slug']})

    def form_valid(self, form):
        form.instance.product = self.get_object()
        if self.request.user.is_authenticated:
            form.instance.created_by = self.request.user
        form.save()

        messages.add_message(self.request, messages.SUCCESS, _('Your comment successfully added'))

        return super(ProductView, self).form_valid(form)

    def get_queryset(self):
        time_threshold = timezone.now() - timedelta(hours=settings.COMMENTS_TIME_THRESHOLD)
        queryset = Product.objects.filter(slug=self.kwargs['slug']).prefetch_related(
            'likes',
            Prefetch('comments', queryset=Comment.objects.filter(
                created_at__gt=time_threshold
            ).select_related('created_by').order_by('-created_at')),
        )

        return queryset


class ProductLikeView(LoginRequiredMixin, View):

    def post(self, request, **kwargs):
        product = get_object_or_404(Product, slug=kwargs['slug'])

        user_liked = request.user.product_likes.filter(slug=kwargs['slug']).exists()
        if user_liked:
            messages.add_message(request, messages.INFO, _('You already liked this product'))
        else:
            product.likes.add(request.user)
            messages.add_message(request, messages.SUCCESS, _('Your like successfully added'))

        return redirect('products:detail', kwargs['slug'])

test_products/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

test_products/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}PRODUCTS{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/project.css' %}">

    {% block css %}{% endblock css %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">PRODUCTS</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:list' %}">{% trans 'Products' %}</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Placed at the end of the document so the pages load faster -->
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/tether.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascript %}{% endblock javascript %}
  </body>
</html>

test_products/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

test_products/templates/bootstrap4/layout/field_errors.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="form-control-feedback"><strong>{{ error }}</strong></span>
    {% endfor %}
{% endif %}

test_products/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

test_products/templates/pages/home.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <p class="tac"><a href="{% url 'products:list' %}">{% trans 'View products' %}</a></p>
{% endblock content %}

test_products/templates/products/list.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    {% if products %}
        <div id="page_obj_list" class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Description' %}</th>
                        <th width="5%">{% trans 'Price' %}</th>
                        <th>
                            <a href="{% url 'products:list' %}?page={{ page_obj.number }}&sort_direction={% if request.GET.sort_direction == 'desc' %}asc{% elif request.GET.sort_direction == 'asc' %}desc{% else %}asc{% endif %}">
                                <span>
                                {% if request.GET.sort_direction == 'asc' %}
                                    <span class="fa fa-sort-desc">&nbsp;</span>
                                {% elif request.GET.sort_direction == 'desc' %}
                                    <span class="fa fa-sort-asc">&nbsp;</span>
                                {% else %}
                                    <span class="fa fa-minus">&nbsp;</span>
                                {% endif %}
                                {% trans 'Likes' %}
                                </span>
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                            <td>{{ product.description }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.likes_num }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="pagination tac">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.sort_direction %}&sort_direction={{ request.GET.sort_direction }}{% endif %}">{% trans 'previous' %}</a>
                {% endif %}

                <span class="current">
                    {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.sort_direction %}&sort_direction={{ request.GET.sort_direction }}{% endif %}">{% trans 'next' %}</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <div class="alert alert-info">{% trans 'Products not found' %}</div>
    {% endif %}
{% endblock %}

test_products/templates/products/product.html
{% extends 'base.html' %}

{% load i18n crispy_forms_tags humanize %}

{% block content %}
    <div class="row">
        <span class="product_tags tag tag-success">${{ product.price }}</span>
        <span class="product_tags tag tag-default" style="margin-right: 10px;">
            {% trans 'Likes' %}: {{ product.likes.all|length }}
        </span>
        {% if request.user not in product.likes.all %}
            <form class="product_tags" method="post" action="{% url 'products:like' product.slug %}">
                {% csrf_token %}
                <button class="btn btn-link fa fa-heart" type="submit"></button>
            </form>
        {% else %}
            <span class="product_tags fa fa-heart text-danger">&nbsp;</span>
        {% endif %}
        <h3>{{ product.name }}</h3>
        <p>{{ product.description }}</p>
    </div>

    <div class="row">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary pull-xs-right">{% trans "Send" %}</button>
        </form>
    </div>

    {% if product.comments.all %}
        <div class="row">
            <h3>{% trans 'Comments' %}</h3>
            {% for comment in product.comments.all %}
                <div class="card">
                    <div class="card-header">
                        <strong>{{ comment.created_by|default:'Anonymous' }}</strong> <span class="text-muted"> {% trans 'commented' %} {{ comment.created_at|naturaltime }}</span>
                    </div>
                    <div class="card-block">
                        <p class="card-text">{{ comment.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}